language: java
jdk:
  - openjdk11

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)
env:
  global:
    - CODECOV_TOKEN="798ea153-04c2-4dad-b2f0-103084dece87"

# Отправлять уведомление на почту idev9tkov@gmail.com если сборка упала
notifications:
  email:
    recipients:
      -idev9tkov@gmail.com
    on_success: never # default: change
    on_failure: always # default: always